name: Build and deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'requirements.txt'
      - 'mkdocs.common.yml'
      - 'mkdocs.en.yml'
      - 'mkdocs.es.yml'
permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build ES docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.es.yml
      - name: Build EN docs
        uses: ./
        with:
          entrypoint: mkdocs
          args: build --config-file=mkdocs.en.yml  

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Copy redirect index page
        run: sudo cp ./index.html ./site

      - name: Deploy docs to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material